name: CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [lib_release]
  push:
    branches: [master]

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GAR
        uses: docker/login-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          registry: us-central1-docker.pkg.dev
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          # platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            us-central1-docker.pkg.dev/open-wa-31bb1/open-wa/wa-automate:latest
            ghcr.io/smashah/wa-automate:latest
            openwa/wa-automate
